[deployer]
# Address of a funded account that will be used for L1 contract deployment
l1_address = "0x3d1e15a1a55578f7c920884a9943b3b35d0d885b"
# Private key corresponding to the above address.
l1_private_key = "0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924"
# If set to 0xAA skip proof verification -> Only use in dev mode.
pico_contract_verifier = "0x00000000000000000000000000000000000000AA"
# If set to true, it will deploy the contract and override the address above with the deployed one.
pico_deploy_verifier = false
# If set to 0xAA skip proof verification -> Only use in dev mode.
risc0_contract_verifier = "0x00000000000000000000000000000000000000AA"
# If set to 0xAA skip proof verification -> Only use in dev mode.
sp1_contract_verifier = "0x00000000000000000000000000000000000000AA"
# If set to true, it will deploy the contract and override the address above with the deployed one.
sp1_deploy_verifier = false
# If set to false, the salt will be randomized.
salt_is_zero = true

[eth]
rpc_url = "http://localhost:8545"

[watcher]
bridge_address = "0x266ffef34e21a7c4ce2e0e42dc780c2c273ca440"
check_interval_ms = 1000
max_block_step = 5000
l2_proposer_private_key = "0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924"

[proposer]
block_time_ms = 5000
coinbase_address = "0x0007a881CD95B1484fca47615B64803dad620C8d"

[committer]
# Address of a funded account that the sequencer will use to send commit txs to the L1.
l1_address = "0x3d1e15a1a55578f7c920884a9943b3b35d0d885b"
# Private key corresponding to the above address.
l1_private_key = "0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924"
on_chain_proposer_address = "0x52178cfc3db571f60016d43adf47d61c2009fa72"
# How often does the sequencer commit new blocks to the L1.
commit_time_ms = 5000
# 1 Gwei
arbitrary_base_blob_gas_price = 1000000000

[prover_server]
# Address of a funded account that the sequencer will use to send verify txs to the L1.
# Has to be a different account than comitter.l1_address.
l1_address = "0xE25583099BA105D9ec0A67f5Ae86D90e50036425"
# Private key corresponding to the above address.
l1_private_key = "0x39725efee3fb28614de3bacaffe4cc4bd8c436257e2c8bb887c4b5c4be45e76d"
# Set it to 0.0.0.0 to allow connections from other machines.
listen_ip = "127.0.0.1"
listen_port = 3900
dev_mode = true
dev_interval_ms = 5000
