[package]
name = "ethrex-prover-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
ethrex-common.workspace = true
ethrex-vm.workspace = true
ethrex-storage.workspace = true
ethrex-rlp.workspace = true
ethrex-prover.workspace = true
ethrex-l2.workspace = true
ethrex-trie.workspace = true

zkvm_interface = { path = "../zkvm/interface", default-features = false }

serde.workspace = true
hex.workspace = true
serde_json.workspace = true
bytes.workspace = true

tokio = { version = "1.21", default-features = false, features = ["full"] }
reqwest = { version = "0.12.9", features = [
  "json",
  "rustls-tls",
], default-features = false }
clap = { version = "4.5.21", features = ["derive"] }

revm = { version = "19.0.0", features = [
  "serde",
  "std",
  "serde-json",
  "optional_no_base_fee",
  "optional_block_gas_limit",
], default-features = false }

# These dependencies must be kept up to date with the corresponding revm version, otherwise errors may pop up because of trait implementation mismatches
revm-inspectors = { version = "0.15.0" }
derive_more = { version = "1.0.0", features = ["full"] }
revm-primitives = { version = "15.2.0", features = [
  "std",
], default-features = false }
futures-util = "0.3.31"
tokio-utils = "0.1.2"
again = "0.1.2"
lazy_static = "1.5.0"
bincode = "1.3.3"

[features]
risc0 = ["zkvm_interface/build_risc0", "ethrex-prover/build_risc0"]
sp1 = ["zkvm_interface/build_sp1", "zkvm_interface/build_sp1"]
gpu = ["ethrex-prover/gpu"]
l2 = ["ethrex-vm/l2", "zkvm_interface/l2"]
default = ["sp1"]
