include:
  - ../blockchain/dev/docker-compose-dev.yaml

services:
  contract_deployer:
    platform: linux/amd64
    container_name: contract_deployer
    image: ethrex_l2_contract_deployer
    build:
      context: ../../
      args:
        - BUILDPLATFORM=linux/amd64
      dockerfile: ./crates/l2/contracts/Dockerfile
    volumes:
      # NOTE: CI_ETHREX_WORKDIR is defined in crates/l2/Makefile
      - ./contracts:${CI_ETHREX_WORKDIR}/contracts
      - ./.env:${CI_ETHREX_WORKDIR}/.env
      - ../../fixtures/genesis/l1-dev.json:${CI_ETHREX_WORKDIR}/fixtures/genesis/l1-dev.json
      - ../../fixtures/genesis/l2.json:${CI_ETHREX_WORKDIR}/fixtures/genesis/l2.json
      - ../../fixtures/keys/private_keys_l1.txt:${CI_ETHREX_WORKDIR}/fixtures/keys/private_keys_l1.txt
      - ./prover/zkvm/interface/sp1/out/riscv32im-succinct-zkvm-vk:${CI_ETHREX_WORKDIR}/riscv32im-succinct-zkvm-vk
      - ./prover/zkvm/interface/risc0/out/riscv32im-risc0-vk:${CI_ETHREX_WORKDIR}/riscv32im-risc0-vk
    environment:
      - ETHREX_ETH_RPC_URL=http://ethrex_l1:8545
      # NOTE: The paths in the env variables must match those
      # specified in the `volumes:` section
      - ETHREX_DEPLOYER_L1_PRIVATE_KEY=${ETHREX_DEPLOYER_PRIVATE_KEY:-0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924}
      - ETHREX_DEPLOYER_CONTRACTS_PATH=${CI_ETHREX_WORKDIR}/contracts
      - ETHREX_DEPLOYER_ENV_FILE_PATH=${CI_ETHREX_WORKDIR}/.env
      - ETHREX_DEPLOYER_GENESIS_L1_PATH=${CI_ETHREX_WORKDIR}/fixtures/genesis/l1-dev.json
      - ETHREX_DEPLOYER_GENESIS_L2_PATH=${CI_ETHREX_WORKDIR}/fixtures/genesis/l2.json
      - ETHREX_DEPLOYER_PRIVATE_KEYS_FILE_PATH=${CI_ETHREX_WORKDIR}/fixtures/keys/private_keys_l1.txt
      - ETHREX_DEPLOYER_DEPLOY_RICH=${ETHREX_DEPLOYER_DEPLOY_RICH:-false}
      - ETHREX_DEPLOYER_PICO_CONTRACT_VERIFIER=${ETHREX_DEPLOYER_PICO_CONTRACT_VERIFIER:-0x00000000000000000000000000000000000000aa}
      - ETHREX_DEPLOYER_PICO_DEPLOY_VERIFIER=${ETHREX_DEPLOYER_PICO_DEPLOY_VERIFIER:-false}
      - ETHREX_DEPLOYER_RISC0_CONTRACT_VERIFIER=${ETHREX_DEPLOYER_RISC0_CONTRACT_VERIFIER:-0x00000000000000000000000000000000000000aa}
      - ETHREX_DEPLOYER_SP1_CONTRACT_VERIFIER=${ETHREX_DEPLOYER_SP1_CONTRACT_VERIFIER:-0x00000000000000000000000000000000000000aa}
      - ETHREX_DEPLOYER_SP1_DEPLOY_VERIFIER=${ETHREX_DEPLOYER_SP1_DEPLOY_VERIFIER:-false}
      - ETHREX_DEPLOYER_ALIGNED_AGGREGATOR_ADDRESS=${ETHREX_DEPLOYER_ALIGNED_AGGREGATOR_ADDRESS:-0x00000000000000000000000000000000000000aa}
      - ETHREX_SP1_VERIFICATION_KEY_PATH=${CI_ETHREX_WORKDIR}/riscv32im-succinct-zkvm-vk
      - ETHREX_RISC0_VERIFICATION_KEY_PATH=${CI_ETHREX_WORKDIR}/riscv32im-risc0-vk
      - ETHREX_DEPLOYER_TDX_CONTRACT_VERIFIER=${ETHREX_DEPLOYER_TDX_CONTRACT_VERIFIER:-0x00000000000000000000000000000000000000aa}
      - ETHREX_DEPLOYER_TDX_DEPLOY_VERIFIER=${ETHREX_DEPLOYER_TDX_DEPLOY_VERIFIER:-false}
      - ETHREX_TDX_DEV_MODE=${ETHREX_TDX_DEV_MODE:-false}
      - ETHREX_ON_CHAIN_PROPOSER_OWNER=0x03d0a0aee676cc45bf7032649e0871927c947c8e
      - ETHREX_BRIDGE_OWNER=0x03d0a0aee676cc45bf7032649e0871927c947c8e
      - ETHREX_DEPLOYER_SEQUENCER_REGISTRY_OWNER=0x03d0a0aee676cc45bf7032649e0871927c947c8e
      - ETHREX_DEPLOYER_DEPLOY_BASED_CONTRACTS=${ETHREX_DEPLOYER_DEPLOY_BASED_CONTRACTS:-false}
      - ETHREX_L2_VALIDIUM=${ETHREX_L2_VALIDIUM:-false}
    depends_on:
      - ethrex

  ethrex_l2:
    restart: always
    container_name: ethrex_l2
    image: "ethrex_l2"
    build:
      context: ../../
      dockerfile: ./crates/l2/Dockerfile
    ports:
      # RPC
      - 127.0.0.1:1729:1729
      # Proposer
      - 127.0.0.1:3900:3900
    environment:
      # Default values are taken from cmd/ethrex/l2/options.rs defaults.
      - ETHREX_ETH_RPC_URL=http://ethrex_l1:8545
      - ETHREX_L2_VALIDIUM=${ETHREX_L2_VALIDIUM:-false}
      - ETHREX_BLOCK_PRODUCER_BLOCK_TIME=${ETHREX_BLOCK_PRODUCER_BLOCK_TIME:-5000}
      - ETHREX_DEPLOYER_PICO_DEPLOY_VERIFIER=${ETHREX_DEPLOYER_PICO_DEPLOY_VERIFIER:-false}
      - ETHREX_PROOF_COORDINATOR_DEV_MODE=${ETHREX_PROOF_COORDINATOR_DEV_MODE:-false}
      - ETHREX_WATCHER_BLOCK_DELAY=${ETHREX_WATCHER_BLOCK_DELAY:-0}
      - ETHREX_BASED=${ETHREX_BASED:-false}
      - ETHREX_STATE_UPDATER_SEQUENCER_REGISTRY=${ETHREX_STATE_UPDATER_SEQUENCER_REGISTRY:-0x0000000000000000000000000000000000000000}
      - ETHREX_COMMITTER_COMMIT_TIME=${ETHREX_COMMITTER_COMMIT_TIME:-60000}
    volumes:
      - ../../fixtures/genesis/l2.json:/genesis/l2.json
      - ./.env:/.env:ro
      - ./config.toml:/config.toml:ro
    # ETHREX_WATCHER_BRIDGE_ADDRESS and ETHREX_COMMITTER_ON_CHAIN_PROPOSER_ADDRESS are set in the .env file by the contract_deployer service.
    command: >
      l2 init
      --network /genesis/l2.json
      --http.addr 0.0.0.0
      --http.port 1729
      --authrpc.port 8552
      --evm levm
      --proof-coordinator.addr 0.0.0.0
      --l1.bridge-address ${ETHREX_WATCHER_BRIDGE_ADDRESS}
      --l1.on-chain-proposer-address ${ETHREX_COMMITTER_ON_CHAIN_PROPOSER_ADDRESS}
      --block-producer.coinbase-address 0x0007a881CD95B1484fca47615B64803dad620C8d
      --committer.l1-private-key 0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924
      --proof-coordinator.l1-private-key 0x39725efee3fb28614de3bacaffe4cc4bd8c436257e2c8bb887c4b5c4be45e76d
