participants:
  - el_type: ethrex
    el_image: ethrex:ci
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v7.1.0
    validator_count: 32
    ethereum_metrics_exporter_enabled: true
  - el_type: ethrex
    el_image: ethrex:ci
    cl_type: teku
    cl_image: consensys/teku:25.6.0
    validator_count: 32
    ethereum_metrics_exporter_enabled: true
  - el_type: ethrex
    el_image: ethrex:ci
    cl_type: prysm
    cl_image: gcr.io/offchainlabs/prysm/beacon-chain:v6.0.4
    validator_count: 32
    ethereum_metrics_exporter_enabled: true

network_params:
  # The address of the staking contract address on the Eth1 chain
  deposit_contract_address: "0x4242424242424242424242424242424242424242"
  seconds_per_slot: 3

additional_services:
  - assertoor
  - dora

assertoor_params:
  tests:
    - https://raw.githubusercontent.com/lambdaclass/ethrex/refs/heads/main/.github/config/assertoor/el-stability-check.yaml # Check that all el clients are synced with the corresponding cl
    - https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/stable/blob-transactions-test.yaml
    - https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/stable/eoa-transactions-test.yaml
