participants:
  - el_type: geth
    el_image: ethereum/client-go:v1.15.2
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v7.0.0-beta.0
    validator_count: 32
    count: 2
  - el_type: ethrex
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v7.0.0-beta.0
    validator_count: 32

network_params:
  # The address of the staking contract address on the Eth1 chain
  deposit_contract_address: "0x4242424242424242424242424242424242424242"

additional_services:
  - assertoor
  - tx_spammer
  - dora

network_params:
  electra_fork_epoch: 1

assertoor_params:
  run_stability_check: false
  run_block_proposal_check: false
  tests:
    - https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/stable/blob-transactions-test.yaml
    - https://raw.githubusercontent.com/lambdaclass/ethrex/refs/heads/main/.github/config/assertoor/el-stability-check.yaml

tx_spammer_params:
  tx_spammer_extra_args: ["--txcount=3", "--accounts=80"]
