participants:
  - el_type: geth
    el_image: ethereum/client-go:v1.16.1
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v7.1.0
    validator_count: 32
  - el_type: ethrex
    el_image: ethrex:ci
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v7.1.0
    validator_count: 32

additional_services:
  - assertoor
  - spamoor
#   - dora
#   - prometheus_grafana
# ethereum_metrics_exporter_enabled: true
# Uncomment the previous lines to enable metrics dashboards and dora explorer, useful for local testing

spamoor_params:
  spammers:
    - scenario: blobs
      config:
        # The eip limits our blob transactions to 6 per block, so for max transactions we keep it at that
        throughput: 6

network_params:
  # The address of the staking contract address on the Eth1 chain
  deposit_contract_address: "0x4242424242424242424242424242424242424242"

assertoor_params:
  run_stability_check: false
  run_block_proposal_check: false
  tests:
    - https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/stable/eoa-transactions-test.yaml
