[package]
name = "zkvm_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_with.workspace = true
serde_json = "1.0.117"
thiserror = "2.0.9"
rkyv.workspace = true

ethrex-common = { path = "../../../../common/", default-features = false }
ethrex-blockchain = { path = "../../../../blockchain/", default-features = false }
ethrex-vm = { path = "../../../../vm", default-features = false }
ethrex-rlp = { path = "../../../../common/rlp", default-features = false }
ethrex-storage = { path = "../../../../storage", default-features = false }
ethrex-trie = { path = "../../../../common/trie", default-features = false }
ethrex-l2-common = { path = "../../../common", default-features = false }

[build-dependencies]
hex.workspace = true
risc0-build = { version = "=2.3.1", optional = true }
risc0-zkvm = { version = "=2.3.1", optional = true }
sp1-build = { version = "=5.0.8", optional = true }
sp1-sdk = { version = "=5.0.8", optional = true }

[package.metadata.risc0]
methods = ["risc0"]

[features]
default = []
risc0 = ["dep:risc0-build", "dep:risc0-zkvm"]
sp1 = ["dep:sp1-build", "dep:sp1-sdk"]
l2 = []
c-kzg = ["ethrex-vm/c-kzg", "ethrex-common/c-kzg"]

[lib]
path = "./src/lib.rs"
