[package]
name = "zkvm-risc0-program"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
risc0-zkvm = { version = "=3.0.3", default-features = false, features = [
    "std", "getrandom"
] }
risc0-zkvm-platform = { version = "=2.2.1", default-features = false, features = [
    "sys-getenv",
] }
guest_program = { path = "../../", default-features = false, features = [
    "c-kzg",
] }
rkyv = { version = "0.8.10", features = ["unaligned"] }


ethrex-common = { path = "../../../../../../common", default-features = false }
ethrex-storage = { path = "../../../../../../storage", default-features = false }
ethrex-rlp = { path = "../../../../../../common/rlp" }
ethrex-vm = { path = "../../../../../../vm", default-features = false, features = [
    "c-kzg",
] }
ethrex-blockchain = { path = "../../../../../../blockchain", default-features = false }
ethrex-l2-common = { path = "../../../../../common", default-features = false }

[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.4-risczero.0" }
ed25519-dalek = { git = "https://github.com/risc0/curve25519-dalek", tag = "curve25519-4.1.2-risczero.0" }
rsa = { git = "https://github.com/risc0/RustCrypto-RSA", tag = "v0.9.6-risczero.0" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
c-kzg = { git = "https://github.com/risc0/c-kzg-4844", tag = "c-kzg/v1.0.3-risczero.1" }


# These precompiles require the "unstable" risc0 feature which is not suited
# for production environments.
# tiny-keccak = { git = "https://github.com/risc0/tiny-keccak", tag = "tiny-keccak/v2.0.2-risczero.0" }
# blst = { git = "https://github.com/risc0/blst", tag = "blst/v0.3.14-risczero.0" }
# p256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "p256/v0.13.2-risczero.0" }
# substrate-bn = { git = "https://github.com/risc0/paritytech-bn", tag = "v0.6.0-risczero.0" }
# [patch."https://github.com/lambdaclass/bls12_381"]
# bls12_381 = { git = "https://github.com/lambdaclass/zkcrypto-bls12_381", branch = "expose-fp-struct" }

[features]
l2 = ["guest_program/l2"]
