[package]
name = "ethrex-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum.workspace = true
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio.workspace = true
bytes.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ethrex-common.workspace = true
ethrex-storage.workspace = true
ethrex-vm.workspace = true
ethrex-blockchain.workspace = true
ethrex-p2p.workspace = true
ethrex-rlp.workspace = true
hex.workspace = true
axum-extra = { version = "0.10.0", features = ["typed-header"] }
jsonwebtoken.workspace = true
rand.workspace = true
tokio-util.workspace = true
reqwest.workspace = true
k256 = { version = "0.13.3", features = ["ecdh"] }
sha3 = "0.10.8"
sha2.workspace = true

# Clients
envy = "0.4.2"
thiserror.workspace = true
secp256k1.workspace = true
keccak-hash.workspace = true

cfg-if.workspace = true

[dev-dependencies]
hex-literal = "0.4.1"

[lib]
path = "./rpc.rs"

[features]
based = ["l2"]
l2 = []
