[package]
name = "ethrex-rpc"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum.workspace = true
tower-http = { version = "0.6.2", features = ["cors"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = { workspace = true, features = ["full"] }
bytes.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ethrex-common.workspace = true
ethrex-storage.workspace = true
ethrex-vm.workspace = true
ethrex-blockchain.workspace = true
ethrex-p2p.workspace = true
ethrex-rlp.workspace = true
ethrex-storage-rollup = { workspace = true, optional = true }
ethrex-l2-common = { workspace = true, optional = true }
ethereum-types.workspace = true
hex.workspace = true
axum-extra = { version = "0.10.0", features = ["typed-header"] }
jsonwebtoken.workspace = true
rand.workspace = true
tokio-util = { workspace = true, features = ["codec"] }
reqwest.workspace = true
k256 = { version = "0.13.3", features = ["ecdh"] }
sha3 = "0.10.8"
sha2.workspace = true

# Clients
envy = "0.4.2"
thiserror.workspace = true
secp256k1.workspace = true
keccak-hash.workspace = true

cfg-if.workspace = true

[dev-dependencies]
hex-literal = "0.4.1"

[lib]
path = "./lib.rs"

[features]
l2 = ["ethrex-storage-rollup", "ethrex-l2-common"]

[lints.clippy] 
unwrap_used = "deny" 
