[package]
name = "ethrex-l2-rpc"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethrex-common.workspace = true
ethrex-storage.workspace = true
ethrex-blockchain.workspace = true
ethrex-p2p.workspace = true
ethrex-storage-rollup.workspace = true
ethrex-l2-common.workspace = true
ethrex-rpc.workspace = true
ethrex-rlp.workspace = true

axum.workspace = true
tower-http.workspace = true
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = { workspace = true, features = ["full"] }
bytes.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
secp256k1.workspace = true
keccak-hash.workspace = true
reqwest.workspace = true
ethereum-types.workspace = true
hex.workspace = true
rustc-hex.workspace = true
url.workspace = true

[lib]
path = "./lib.rs"

[features]

[lints.clippy]
unwrap_used = "deny"
