[package]
name = "ethrex-vm"
version.workspace = true
edition.workspace = true

[dependencies]
ethrex-common.workspace = true
ethrex-storage.workspace = true
ethrex-levm.workspace = true
ethrex-trie.workspace = true
ethrex-rlp.workspace = true

revm = { version = "19.0.0", features = [
  "serde",
  "std",
  "serde-json",
  "optional_no_base_fee",
  "optional_block_gas_limit",
], default-features = false }

# These dependencies must be kept up to date with the corresponding revm version, otherwise errors may pop up because of trait implementation mismatches
revm-inspectors = { version = "0.15.0" }
revm-primitives = { version = "15.2.0", features = [
  "std",
], default-features = false }
bytes.workspace = true
thiserror.workspace = true
hex.workspace = true
lazy_static.workspace = true
cfg-if.workspace = true
tracing.workspace = true

serde.workspace = true
bincode = "1"

ethereum-types.workspace = true

[lib]
path = "./vm.rs"

[features]
default = []
l2 = []
c-kzg = ["revm/c-kzg", "ethrex-levm/c-kzg", "ethrex-common/c-kzg"]
blst = ["revm/blst"]

[profile.test]
opt-level = 3
