[package]
name = "ethrex-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
ethrex-common.workspace = true
ethrex-levm.workspace = true
ethrex-trie.workspace = true
ethrex-rlp.workspace = true

revm = { version = "19.0.0", features = [
    "serde",
    "std",
    "serde-json",
    "optional_no_base_fee",
    "optional_block_gas_limit",
], default-features = false }

# These dependencies must be kept up to date with the corresponding revm version, otherwise errors may pop up because of trait implementation mismatches
revm-inspectors = { version = "0.15.0" }
derive_more = { version = "1.0.0", features = ["full"] }
revm-primitives = { version = "15.2.0", features = [
    "std",
], default-features = false }
bytes.workspace = true
thiserror.workspace = true
hex.workspace = true
lazy_static.workspace = true
cfg-if.workspace = true
tracing.workspace = true
serde.workspace = true
sha3.workspace = true

bincode = "1"
dyn-clone = "1.0"

ethereum-types.workspace = true

[lib]
path = "./lib.rs"

[features]
default = []
l2 = ["ethrex-levm/l2"]
c-kzg = ["revm/c-kzg", "ethrex-levm/c-kzg", "ethrex-common/c-kzg"]
blst = ["revm/blst"]
debug = ["ethrex-levm/debug"]

[lints.clippy]
unwrap_used = "deny"
