[package]
name = "ethrex-replay"
version = "0.1.0"
edition = "2024"

[dependencies]
ethrex-common.workspace = true
ethrex-vm.workspace = true
ethrex-trie.workspace = true
ethrex-levm.workspace = true
ethrex-rpc.workspace = true

zkvm_interface = { path = "../../crates/l2/prover/zkvm/interface", default-features = false }
ethrex-prover = { path = "../../crates/l2/prover", default-features = false }

serde.workspace = true
hex.workspace = true
serde_json.workspace = true
bytes.workspace = true
secp256k1.workspace = true

tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
eyre.workspace = true

tokio = { version = "1.21", default-features = false, features = ["full"] }
clap.workspace = true

revm = { version = "19.0.0", features = [
  "serde",
  "std",
  "serde-json",
  "optional_no_base_fee",
  "optional_block_gas_limit",
], default-features = false }

# These dependencies must be kept up to date with the corresponding revm version, otherwise errors may pop up because of trait implementation mismatches
revm-inspectors = { version = "0.15.0" }
derive_more = { version = "1.0.0", features = ["full"] }
revm-primitives = { version = "15.2.0", features = [
  "std",
], default-features = false }
futures-util = "0.3.31"
tokio-utils = "0.1.2"
again = "0.1.2"
lazy_static = "1.5.0"
bincode = "1.3.3"
charming = { version = "0.4.0", features = ["ssr"] }


[features]
risc0 = ["zkvm_interface/risc0", "ethrex-prover/risc0"]
sp1 = ["zkvm_interface/sp1", "ethrex-prover/sp1"]
gpu = ["ethrex-prover/gpu"]
l2 = ["zkvm_interface/l2"]
ci = []
