# The reason this exists is because the Pico zkVM compiles in nightly only.
name: L2 Prover (nightly)
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    # "Lint" is a required check, don't change the name
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        action:
          - command: check
            args: -p ethrex-prover -F pico
          - command: clippy
            args: -p ethrex-prover -F pico --all-targets
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Rust toolchain install
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-11-27
          components: rust-src, clippy
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
      # https://pico-docs.brevis.network/getting-started/installation
      - name: Install pico-cli
        uses: baptiste0928/cargo-install@v3
        with:
          crate: pico-cli
          git: https://github.com/brevis-network/pico
      - name: ${{ matrix.action.command }} Command
        run: cargo +nightly-2024-11-27 ${{ matrix.action.command }} ${{ matrix.action.args }}

  test:
    # "Test" is a required check, don't change the name
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Rust toolchain install
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-11-27
          components: rust-src
      # https://pico-docs.brevis.network/getting-started/installation
      - name: Install pico-cli
        uses: baptiste0928/cargo-install@v3
        with:
          crate: pico-cli
          git: https://github.com/brevis-network/pico
      - name: Build
        run: |
          cd crates/l2/prover
          cargo +nightly-2024-11-27 build --release -F pico
      - name: Test Prover Execution
        run: |
          cd crates/l2/prover
          RUST_LOG=info make perf-pico
