name: Replay proving
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    paths:
      - ".github/workflows/main_prover_l1.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DOCKER_ETHREX_WORKDIR: /usr/local/bin

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  test:
    name: Prove an L1 block with ${{ matrix.backend }} backend
    runs-on: gpu
    strategy:
      fail-fast: true
      matrix:
        backend: ["sp1", "risc0"]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust

      - name: RISC-V Risc0 toolchain install
        if: matrix.backend == 'risc0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # should be able to specify a version for `rzup install rust` (toolchain version)
        # but it throws a "error decoding response body" in that case
        run: |
          curl -L https://risczero.com/install | bash
          ~/.risc0/bin/rzup install cargo-risczero 2.3.1
          ~/.risc0/bin/rzup install rust
      - name: RISC-V SP1 toolchain install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.backend == 'sp1'
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up --version 5.0.8

      - name: Build
        run: |
          cd cmd/ethrex_replay
          export PATH=$PATH:/usr/local/cuda-12.8/bin
          cargo b -r --features "${{ matrix.backend }},gpu"

      - name: Run
        env:
          # TODO(): use RPC
          # RPC_URL: $${{ secrets.ETHREX_L2_RPC_URL }}
          RPC_URL: "http://eth-testnet-rpc:8547"
        run: |
          cp fixtures/cache/rpc_prover/cache_hoodi_1132599.bin cmd/ethrex_replay
          cd cmd/ethrex_replay
          make prove-${{ matrix.backend }}-gpu-ci BLOCK_NUMBER=1132599 NETWORK=hoodi

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "L1 block proving benchmark"
          tool: "customBiggerIsBetter"
          output-file-path: cmd/ethrex_replay/bench_latest.json
          benchmark-data-dir-path: "benchmarks"
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          comment-on-alert: true

      - name: Ensure admin permissions in _work
        if: always()
        run: sudo chown admin:admin -R /home/admin/actions-runner/_work/
      # - name: Report Status
      #   if: always()
      #   uses: ravsamhq/notify-slack-action@v2
      #   with:
      #     status: ${{ job.status }}
      #     notify_when: 'failure'
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.ETHREX_L2_SLACK_WEBHOOK }}
