name: Benchmark Trie

on:
  workflow_call:
  pull_request:
    branches: ["**"]
    paths:
      - "crates/common/trie/**"

permissions:
  pull-requests: write

jobs:
  build-ethrex-trie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Benchmarks
        uses: boa-dev/criterion-compare-action@v3
        with:
          cwd: "crates/common/trie"
          benchName: "trie_bench"
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
