services:
  prometheus:
    volumes:
      - ../metrics/provisioning/prometheus/prometheus_l2.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9092:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    ports:
      - "3802:3000"
    volumes:
      - ../metrics/provisioning/grafana/dashboards/l2_dashboards:/etc/grafana/provisioning/dashboards/l2_dashboards
      - ../metrics/provisioning/grafana/dashboards/dashboard_config_l2.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL:-http://localhost:3802}
