# example: docker compose -f docker-compose-metrics.yaml -f docker-compose-metrics-l2.override.yaml up
services:
  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml
    #volumes: defined in the .overrides file
    #ports: defined in the .overrides file
  grafana:
    image: grafana/grafana
    volumes:
      - ./provisioning/grafana/datasources:/etc/grafana/provisioning/datasources
    #ports: defined in the .overrides file
    environment:
      - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource
      - L1_RPC_URL=${L1_RPC_URL}
    depends_on:
      - prometheus
